# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3ae069c201a54e710ff3914285c4a1e9132df9a2d1673321fb0f7b89f99581628d6bef34232b199c3083cc09197bf9cdfaf1c333d5c2f6c19a8ac0f3027f4c

test:
  secret_key_base: 29b8f00e21c294b82b5c7ccce139bba50d24007c4bb007aecf4832101b52174341bc440f86c3d1f00ad2c32545418f8d44f0c36e569c4adadb42d119550eeecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
